using System.Collections.Generic;
using PokemonUltimate.Combat.Results;
using PokemonUltimate.Core.Domain.Instances.Pokemon;

namespace PokemonUltimate.Combat.Infrastructure.Events
{
    /// <summary>
    /// Represents a structured battle event that occurred during combat.
    /// Used for statistics, logging, and analysis instead of hardcoded log messages.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.20: Statistics System
    /// **Documentation**: See `docs/features/2-combat-system/2.20-statistics-system/architecture.md`
    /// </remarks>
    public class BattleEvent
    {
        /// <summary>
        /// The type of event that occurred.
        /// </summary>
        public BattleEventType EventType { get; set; }

        /// <summary>
        /// The turn number when this event occurred (1-based).
        /// </summary>
        public int TurnNumber { get; set; }

        /// <summary>
        /// The side that triggered this event (Player or Enemy).
        /// </summary>
        public bool IsPlayerSide { get; set; }

        /// <summary>
        /// The Pokemon involved in this event (can be null for field events).
        /// </summary>
        public PokemonInstance Pokemon { get; set; }

        /// <summary>
        /// Additional context data specific to the event type.
        /// </summary>
        public BattleEventData Data { get; set; }

        /// <summary>
        /// Creates a new battle event.
        /// </summary>
        public BattleEvent(BattleEventType eventType, int turnNumber, bool isPlayerSide, PokemonInstance pokemon = null, BattleEventData data = null)
        {
            EventType = eventType;
            TurnNumber = turnNumber;
            IsPlayerSide = isPlayerSide;
            Pokemon = pokemon;
            Data = data ?? new BattleEventData();
        }
    }

    /// <summary>
    /// Types of battle events that can occur.
    /// </summary>
    public enum BattleEventType
    {
        // Pokemon Events
        PokemonFainted,
        PokemonSwitched,
        PokemonHealed,
        PokemonStatusApplied,

        // Team Events
        TeamStatusChanged,  // Pokemon remaining count changed

        // AI Decision Events
        AIDecisionMade,     // AI made a decision (attack, switch, etc.)

        // Move Events
        MoveUsed,
        MoveMissed,
        CriticalHit,

        // Damage Events
        DamageDealt,

        // Turn Events
        TurnStarted,
        TurnEnded,

        // Battle Events
        BattleStarted,
        BattleEnded,

        // Action Processing Events
        ActionCollected,    // Action was collected from AI/player
        ActionsSorted,      // Actions were sorted by priority/speed
        ActionsGenerated,   // Actions were generated by a move execution
    }

    /// <summary>
    /// Additional data for battle events, structured by event type.
    /// </summary>
    public class BattleEventData
    {
        // For PokemonFainted
        public PokemonInstance DefeatedBy { get; set; }
        public int RemainingPokemon { get; set; }
        public int TotalPokemon { get; set; }
        public int FaintedCount { get; set; }

        // For PokemonSwitched
        public PokemonInstance SwitchedOut { get; set; }
        public PokemonInstance SwitchedIn { get; set; }

        // For AIDecisionMade
        public string DecisionType { get; set; }  // "ATTACK", "STRATEGIC_SWITCH", "MANDATORY_SWITCH", etc.
        public string DecisionReason { get; set; }
        public string MoveName { get; set; }
        public PokemonInstance TargetPokemon { get; set; }

        // For MoveUsed / DamageDealt
        public string MoveId { get; set; }
        public int DamageAmount { get; set; }
        public bool WasCritical { get; set; }
        public float TypeEffectiveness { get; set; }

        // Detailed damage calculation info
        public float BaseDamage { get; set; }
        public float Multiplier { get; set; }
        public int HpBefore { get; set; }
        public int HpAfter { get; set; }
        public bool IsSelfDamage { get; set; }  // True if damage is self-inflicted (status damage, recoil, etc.)

        // For PokemonHealed
        public int HealAmount { get; set; }

        // For PokemonStatusApplied
        public string StatusName { get; set; }

        // For BattleEnded
        public BattleOutcome Outcome { get; set; }
        public int TotalTurns { get; set; }

        // Team statistics for battle end (Player side)
        // Note: Enemy statistics would need separate fields or a different approach
        public int PlayerFainted { get; set; }
        public int PlayerTotal { get; set; }
        public int EnemyFainted { get; set; }
        public int EnemyTotal { get; set; }

        // For ActionCollected / ActionsSorted
        public string ActionType { get; set; }
        public int Priority { get; set; }
        public float Speed { get; set; }
        public int SlotIndex { get; set; }
        public int ActionCount { get; set; }

        // For ActionsGenerated
        public string GeneratedActionTypes { get; set; }  // Comma-separated list of action type names
        public int GeneratedActionCount { get; set; }

        // For ActionsSorted - detailed information about each action
        public List<string> SortedActionsDetails { get; set; }  // List of action descriptions with priority, speed, etc.

        // For BattleStarted (setup information)
        public int PlayerSlots { get; set; }
        public int EnemySlots { get; set; }
        public int PlayerPartySize { get; set; }
        public int EnemyPartySize { get; set; }
        public string BattleMode { get; set; }  // "Singles", "Doubles", "Triples", "Horde", "Custom"
    }
}
