using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Engine.Processors.Definition;
using PokemonUltimate.Combat.Field;
using PokemonUltimate.Combat.Handlers.Registry;
using PokemonUltimate.Combat.Utilities.Extensions;
using PokemonUltimate.Core.Data.Constants;
using PokemonUltimate.Core.Data.Enums;

namespace PokemonUltimate.Combat.Engine.Processors
{
    /// <summary>
    /// Processes everything that happens at the end of each turn:
    /// - Abilities (Speed Boost, etc.)
    /// - Items (Leftovers, Black Sludge, etc.)
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.6: Combat Engine
    /// **Documentation**: See `docs/features/2-combat-system/2.6-combat-engine/architecture.md`
    /// </remarks>
    public class TurnEndProcessor : IActionGeneratingPhaseProcessor
    {
        private readonly CombatEffectHandlerRegistry _handlerRegistry;

        /// <summary>
        /// Creates a new TurnEndProcessor.
        /// </summary>
        /// <param name="handlerRegistry">The handler registry. If null, creates and initializes a new one.</param>
        public TurnEndProcessor(CombatEffectHandlerRegistry handlerRegistry = null)
        {
            _handlerRegistry = handlerRegistry ?? CombatEffectHandlerRegistry.CreateDefault();
        }

        /// <summary>
        /// Gets the phase this processor handles.
        /// </summary>
        public BattlePhase Phase => BattlePhase.TurnEnd;

        /// <summary>
        /// Processes abilities and items that activate at the end of each turn.
        /// </summary>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>List of actions generated by abilities and items.</returns>
        /// <exception cref="ArgumentNullException">If field is null.</exception>
        public async Task<List<BattleAction>> ProcessAsync(BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field), ErrorMessages.FieldCannotBeNull);

            var actions = new List<BattleAction>();

            // Get all active slots ordered by speed (fastest first)
            var activeSlots = field.GetAllActiveSlots()
                .Where(slot => slot.IsActive())
                .OrderByDescending(slot => slot.Pokemon.GetEffectiveStat(Stat.Speed))
                .ToList();

            foreach (var slot in activeSlots)
            {
                var pokemon = slot.Pokemon;

                // Process ability (if exists) using handler registry
                if (pokemon.Ability != null)
                {
                    var abilityActions = _handlerRegistry.ProcessAbility(
                        pokemon.Ability, slot, field, AbilityTrigger.OnTurnEnd);
                    actions.AddRange(abilityActions);
                }

                // Process held item (if exists) using handler registry
                if (pokemon.HeldItem != null)
                {
                    var itemActions = _handlerRegistry.ProcessItem(
                        pokemon.HeldItem, slot, field, ItemTrigger.OnTurnEnd);
                    actions.AddRange(itemActions);
                }
            }

            return await Task.FromResult(actions);
        }
    }
}
