using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Extensions;
using PokemonUltimate.Content.Extensions;
using PokemonUltimate.Core.Data.Blueprints;
using PokemonUltimate.Core.Data.Enums;
using PokemonUltimate.Core.Utilities.Extensions;
using PokemonUltimate.Core.Domain.Instances.Pokemon;
using PokemonUltimate.Core.Data.Constants;
using PokemonUltimate.Core.Infrastructure.Localization;

namespace PokemonUltimate.Combat.Processors.Phases
{
    /// <summary>
    /// Processes everything that happens at the end of each turn:
    /// - Abilities (Speed Boost, etc.)
    /// - Items (Leftovers, Black Sludge, etc.)
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.6: Combat Engine
    /// **Documentation**: See `docs/features/2-combat-system/2.6-combat-engine/architecture.md`
    /// </remarks>
    public class TurnEndProcessor : IActionGeneratingPhaseProcessor
    {
        /// <summary>
        /// Gets the phase this processor handles.
        /// </summary>
        public BattlePhase Phase => BattlePhase.TurnEnd;

        /// <summary>
        /// Processes abilities and items that activate at the end of each turn.
        /// </summary>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>List of actions generated by abilities and items.</returns>
        /// <exception cref="ArgumentNullException">If field is null.</exception>
        public async Task<List<BattleAction>> ProcessAsync(BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field), ErrorMessages.FieldCannotBeNull);

            var actions = new List<BattleAction>();

            // Get all active slots ordered by speed (fastest first)
            var activeSlots = field.GetAllActiveSlots()
                .Where(slot => slot.IsActive())
                .OrderByDescending(slot => slot.Pokemon.GetEffectiveStat(Stat.Speed))
                .ToList();

            foreach (var slot in activeSlots)
            {
                var pokemon = slot.Pokemon;

                // Process ability (if exists)
                if (pokemon.Ability != null)
                {
                    var abilityActions = ProcessAbility(pokemon.Ability, slot, field);
                    actions.AddRange(abilityActions);
                }

                // Process held item (if exists)
                if (pokemon.HeldItem != null)
                {
                    var itemActions = ProcessItem(pokemon.HeldItem, slot, field);
                    actions.AddRange(itemActions);
                }
            }

            return await Task.FromResult(actions);
        }

        /// <summary>
        /// Processes an ability for end-of-turn effects.
        /// </summary>
        private List<BattleAction> ProcessAbility(AbilityData ability, BattleSlot slot, BattleField field)
        {
            var actions = new List<BattleAction>();

            // Check if this ability listens to OnTurnEnd trigger
            if (!ability.ListensTo(AbilityTrigger.OnTurnEnd))
                return actions;

            // Process based on ability effect
            switch (ability.Effect)
            {
                case AbilityEffect.RaiseOwnStat:
                    // Example: Speed Boost
                    actions.AddRange(ProcessRaiseOwnStat(ability, slot, field));
                    break;

                    // Add other ability effects as needed
            }

            return actions;
        }

        /// <summary>
        /// Processes an item for end-of-turn effects.
        /// </summary>
        private List<BattleAction> ProcessItem(ItemData item, BattleSlot slot, BattleField field)
        {
            var actions = new List<BattleAction>();

            // Check if this item listens to OnTurnEnd trigger
            if (!item.ListensTo(ItemTrigger.OnTurnEnd))
                return actions;

            // Process healing items (Leftovers, Black Sludge)
            if (item.HealAmount > 0)
            {
                actions.AddRange(ProcessHealEachTurn(item, slot, field));
            }

            return actions;
        }

        /// <summary>
        /// Processes RaiseOwnStat ability effect (e.g., Speed Boost).
        /// </summary>
        private List<BattleAction> ProcessRaiseOwnStat(AbilityData ability, BattleSlot slot, BattleField field)
        {
            var actions = new List<BattleAction>();

            if (ability.TargetStat == null)
                return actions;

            var pokemon = slot.Pokemon;
            var currentStatStage = slot.GetStatStage(ability.TargetStat.Value);

            // Check if stat is already maxed (+6 stages)
            if (currentStatStage >= 6)
                return actions;

            // Message for ability activation
            var provider = LocalizationService.Instance;
            var abilityName = ability.GetDisplayName(provider);
            actions.Add(new MessageAction(
                provider.GetString(LocalizationKey.AbilityActivated, pokemon.DisplayName, abilityName)));

            // Raise own stat
            actions.Add(new StatChangeAction(slot, slot, ability.TargetStat.Value, ability.StatStages));

            return actions;
        }

        /// <summary>
        /// Processes HealEachTurn item effect (e.g., Leftovers, Black Sludge).
        /// </summary>
        private List<BattleAction> ProcessHealEachTurn(ItemData item, BattleSlot slot, BattleField field)
        {
            var actions = new List<BattleAction>();
            var pokemon = slot.Pokemon;

            // Don't heal if already at full HP
            if (pokemon.CurrentHP >= pokemon.MaxHP)
                return actions;

            // Calculate heal amount
            int healAmount = CalculateHealAmount(item, pokemon);

            // Message for item activation
            var provider = LocalizationService.Instance;
            var itemName = item.GetLocalizedName(provider);
            actions.Add(new MessageAction(
                provider.GetString(LocalizationKey.ItemActivated, pokemon.DisplayName, itemName)));

            // Healing action
            actions.Add(new HealAction(slot, slot, healAmount));

            return actions;
        }

        /// <summary>
        /// Calculates heal amount for an item.
        /// </summary>
        private int CalculateHealAmount(ItemData item, PokemonInstance pokemon)
        {
            if (item.HealAmount > 0)
                return item.HealAmount;

            // Default: Leftovers-style (1/16)
            return Math.Max(1, pokemon.MaxHP / 16);
        }
    }
}
