using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Engine.Processors.Definition;
using PokemonUltimate.Combat.Field;
using PokemonUltimate.Combat.Utilities.Extensions;
using PokemonUltimate.Core.Data.Blueprints;
using PokemonUltimate.Core.Data.Constants;
using PokemonUltimate.Core.Data.Enums;

namespace PokemonUltimate.Combat.Engine.Processors
{
    /// <summary>
    /// Processes abilities and items that activate when weather changes.
    /// Note: Speed boosts from weather (Swift Swim, Chlorophyll) are passive and handled
    /// in speed calculations, not here. This processor handles active effects.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.6: Combat Engine
    /// **Documentation**: See `docs/features/2-combat-system/2.6-combat-engine/architecture.md`
    /// </remarks>
    public class WeatherChangeProcessor : IActionGeneratingPhaseProcessor
    {
        /// <summary>
        /// Gets the phase this processor handles.
        /// </summary>
        public BattlePhase Phase => BattlePhase.WeatherChange;

        /// <summary>
        /// Processes abilities and items that activate when weather changes.
        /// </summary>
        /// <param name="field">The battlefield.</param>
        /// <returns>List of actions generated.</returns>
        public List<BattleAction> ProcessWeatherChange(BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field), ErrorMessages.FieldCannotBeNull);

            var actions = new List<BattleAction>();

            // Get all active slots ordered by speed (fastest first)
            var activeSlots = field.GetAllActiveSlots()
                .Where(slot => slot.IsActive())
                .OrderByDescending(slot => slot.Pokemon.GetEffectiveStat(Stat.Speed))
                .ToList();

            foreach (var slot in activeSlots)
            {
                var pokemon = slot.Pokemon;

                // Process ability
                if (pokemon.Ability != null)
                {
                    var abilityActions = ProcessAbility(pokemon.Ability, slot, field);
                    actions.AddRange(abilityActions);
                }

                // Process item
                if (pokemon.HeldItem != null)
                {
                    var itemActions = ProcessItem(pokemon.HeldItem, slot, field);
                    actions.AddRange(itemActions);
                }
            }

            return actions;
        }

        /// <summary>
        /// Processes the weather-change phase (required by interface).
        /// </summary>
        /// <param name="field">The battlefield.</param>
        /// <returns>List of actions generated by weather change.</returns>
        public async Task<List<BattleAction>> ProcessAsync(BattleField field)
        {
            return await Task.FromResult(ProcessWeatherChange(field));
        }

        /// <summary>
        /// Processes an ability for weather-change effects.
        /// </summary>
        private List<BattleAction> ProcessAbility(AbilityData ability, BattleSlot slot, BattleField field)
        {
            var actions = new List<BattleAction>();

            if (!ability.ListensTo(AbilityTrigger.OnWeatherChange))
                return actions;

            // Most weather-related abilities are passive (SpeedBoostInWeather)
            // and don't need active processing here. They're handled in speed calculations.
            // This processor is for any active effects that need to happen on weather change.

            switch (ability.Effect)
            {
                // Add ability effects that need active processing on weather change
                // Most are passive and handled elsewhere
                default:
                    // No active effects for weather change
                    break;
            }

            return actions;
        }

        /// <summary>
        /// Processes an item for weather-change effects.
        /// </summary>
        private List<BattleAction> ProcessItem(ItemData item, BattleSlot slot, BattleField field)
        {
            var actions = new List<BattleAction>();

            // Items typically don't activate on weather change
            // Add item effects as needed

            return actions;
        }
    }
}
