using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Engine.Processors.Definition;
using PokemonUltimate.Combat.Field;
using PokemonUltimate.Combat.Handlers.Registry;
using PokemonUltimate.Combat.Utilities.Extensions;
using PokemonUltimate.Core.Data.Constants;
using PokemonUltimate.Core.Data.Enums;

namespace PokemonUltimate.Combat.Engine.Processors
{
    /// <summary>
    /// Processes abilities and items that activate when weather changes.
    /// Note: Speed boosts from weather (Swift Swim, Chlorophyll) are passive and handled
    /// in speed calculations, not here. This processor handles active effects.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.6: Combat Engine
    /// **Documentation**: See `docs/features/2-combat-system/2.6-combat-engine/architecture.md`
    /// </remarks>
    public class WeatherChangeProcessor : IActionGeneratingPhaseProcessor
    {
        private readonly CombatEffectHandlerRegistry _handlerRegistry;

        /// <summary>
        /// Creates a new WeatherChangeProcessor.
        /// </summary>
        /// <param name="handlerRegistry">The handler registry. If null, creates and initializes a new one.</param>
        public WeatherChangeProcessor(CombatEffectHandlerRegistry handlerRegistry = null)
        {
            _handlerRegistry = handlerRegistry ?? CombatEffectHandlerRegistry.CreateDefault();
        }

        /// <summary>
        /// Gets the phase this processor handles.
        /// </summary>
        public BattlePhase Phase => BattlePhase.WeatherChange;

        /// <summary>
        /// Processes abilities and items that activate when weather changes.
        /// </summary>
        /// <param name="field">The battlefield.</param>
        /// <returns>List of actions generated.</returns>
        public List<BattleAction> ProcessWeatherChange(BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field), ErrorMessages.FieldCannotBeNull);

            var actions = new List<BattleAction>();

            // Get all active slots ordered by speed (fastest first)
            var activeSlots = field.GetAllActiveSlots()
                .Where(slot => slot.IsActive())
                .OrderByDescending(slot => slot.Pokemon.GetEffectiveStat(Stat.Speed))
                .ToList();

            foreach (var slot in activeSlots)
            {
                var pokemon = slot.Pokemon;

                // Process ability using handler registry
                if (pokemon.Ability != null)
                {
                    var abilityActions = _handlerRegistry.ProcessAbility(
                        pokemon.Ability, slot, field, AbilityTrigger.OnWeatherChange);
                    actions.AddRange(abilityActions);
                }

                // Note: Items don't typically activate on weather change
                // Most weather-related effects are passive abilities handled in speed calculations
            }

            return actions;
        }

        /// <summary>
        /// Processes the weather-change phase (required by interface).
        /// </summary>
        /// <param name="field">The battlefield.</param>
        /// <returns>List of actions generated by weather change.</returns>
        public async Task<List<BattleAction>> ProcessAsync(BattleField field)
        {
            return await Task.FromResult(ProcessWeatherChange(field));
        }
    }
}
