using System;
using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Field;
using PokemonUltimate.Combat.Utilities.Extensions;
using PokemonUltimate.Content.Catalogs.Field;
using PokemonUltimate.Core.Data.Blueprints;
using PokemonUltimate.Core.Domain.Instances.Pokemon;
using PokemonUltimate.Localization.Constants;
using PokemonUltimate.Localization.Extensions;
using PokemonUltimate.Localization.Services;

namespace PokemonUltimate.Combat.Handlers.Effects
{
    /// <summary>
    /// Handler para procesar curación de terreno al final del turno (Grassy Terrain).
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.8: End-of-Turn Effects
    /// **Documentation**: See `RESPONSIBILITY_REVIEW.md`
    /// </remarks>
    public class TerrainHealingHandler
    {
        /// <summary>
        /// Processes terrain healing for all active Pokemon on the field.
        /// </summary>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>List of actions generated by terrain healing.</returns>
        public List<BattleAction> ProcessTerrainHealing(BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field));

            var actions = new List<BattleAction>();

            // Check if there's active terrain that heals
            if (field.TerrainData == null || !field.TerrainData.HealsEachTurn)
                return actions;

            var terrainData = field.TerrainData;

            // Process all active slots
            foreach (var slot in field.GetAllActiveSlots())
            {
                if (!slot.IsActive())
                    continue;

                var pokemon = slot.Pokemon;

                // Check if Pokemon is grounded (terrain only affects grounded Pokemon)
                if (!IsGrounded(pokemon))
                    continue;

                // Calculate healing amount
                int healing = CalculateTerrainHealing(pokemon.MaxHP, terrainData.EndOfTurnHealing);

                // Only heal if Pokemon is not at full HP and healing amount > 0
                if (pokemon.CurrentHP < pokemon.MaxHP && healing > 0)
                {
                    var provider = LocalizationService.Instance;
                    var terrainName = terrainData.GetDisplayName(provider);
                    actions.Add(new MessageAction(provider.GetString(LocalizationKey.TerrainHealing, pokemon.DisplayName, terrainName)));
                    actions.Add(new HealAction(null, slot, healing)); // null user = system action
                }
            }

            return actions;
        }

        /// <summary>
        /// Checks if a Pokemon is grounded (affected by terrain).
        /// </summary>
        private bool IsGrounded(PokemonInstance pokemon)
        {
            if (pokemon == null)
                return false;

            return TerrainData.IsGrounded(
                pokemon.Species.PrimaryType,
                pokemon.Species.SecondaryType,
                pokemon.Ability?.Id,
                pokemon.HeldItem?.Id);
        }

        /// <summary>
        /// Calculates terrain healing based on Max HP and healing fraction.
        /// </summary>
        private int CalculateTerrainHealing(int maxHP, float healingFraction)
        {
            int healing = (int)(maxHP * healingFraction);
            return Math.Max(0, healing); // Minimum 0 (no negative healing)
        }
    }
}
