using System;
using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Field;
using PokemonUltimate.Combat.Infrastructure.Factories;
using PokemonUltimate.Combat.Utilities.Extensions;
using PokemonUltimate.Content.Catalogs.Field;
using PokemonUltimate.Core.Data.Blueprints;
using PokemonUltimate.Core.Data.Enums;
using PokemonUltimate.Core.Domain.Instances.Pokemon;
using PokemonUltimate.Localization.Constants;
using PokemonUltimate.Localization.Extensions;
using PokemonUltimate.Localization.Services;

namespace PokemonUltimate.Combat.Handlers.Effects
{
    /// <summary>
    /// Handler para procesar daño de clima al final del turno (Sandstorm, Hail).
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.8: End-of-Turn Effects
    /// **Documentation**: See `RESPONSIBILITY_REVIEW.md`
    /// </remarks>
    public class WeatherDamageHandler
    {
        private readonly DamageContextFactory _damageContextFactory;

        /// <summary>
        /// Creates a new WeatherDamageHandler.
        /// </summary>
        /// <param name="damageContextFactory">Factory for creating damage contexts. Cannot be null.</param>
        public WeatherDamageHandler(DamageContextFactory damageContextFactory)
        {
            _damageContextFactory = damageContextFactory ?? throw new ArgumentNullException(nameof(damageContextFactory));
        }

        /// <summary>
        /// Processes weather damage for all active Pokemon on the field.
        /// </summary>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>List of actions generated by weather damage.</returns>
        public List<BattleAction> ProcessWeatherDamage(BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field));

            var actions = new List<BattleAction>();

            // Check if there's active weather that deals damage
            if (field.WeatherData == null || !field.WeatherData.DealsDamage)
                return actions;

            var weatherData = field.WeatherData;

            // Process all active slots
            foreach (var slot in field.GetAllActiveSlots())
            {
                if (!slot.IsActive())
                    continue;

                var pokemon = slot.Pokemon;

                // Check if Pokemon is immune to weather damage by type
                bool isTypeImmune = IsTypeImmuneToWeatherDamage(pokemon, weatherData);

                // Check if Pokemon has ability that grants immunity
                bool hasImmunityAbility = HasWeatherImmunityAbility(pokemon, weatherData);

                // Skip if immune
                if (isTypeImmune || hasImmunityAbility)
                    continue;

                // Calculate and apply weather damage
                int damage = CalculateWeatherDamage(pokemon.MaxHP, weatherData.EndOfTurnDamage);
                string localizationKey = GetWeatherDamageMessageKey(field.Weather);
                var provider = LocalizationService.Instance;

                actions.Add(new MessageAction(provider.GetString(localizationKey, pokemon.DisplayName)));
                actions.Add(CreateStatusDamageAction(slot, field, damage));
            }

            return actions;
        }

        /// <summary>
        /// Checks if a Pokemon's type makes it immune to weather damage.
        /// </summary>
        private bool IsTypeImmuneToWeatherDamage(PokemonInstance pokemon, WeatherData weatherData)
        {
            if (weatherData.DamageImmuneTypes == null || weatherData.DamageImmuneTypes.Length == 0)
                return false;

            // Check primary type
            if (weatherData.IsTypeImmuneToDamage(pokemon.Species.PrimaryType))
                return true;

            // Check secondary type (if exists)
            if (pokemon.Species.SecondaryType.HasValue)
            {
                if (weatherData.IsTypeImmuneToDamage(pokemon.Species.SecondaryType.Value))
                    return true;
            }

            return false;
        }

        /// <summary>
        /// Checks if a Pokemon has an ability that grants immunity to weather damage.
        /// </summary>
        private bool HasWeatherImmunityAbility(PokemonInstance pokemon, WeatherData weatherData)
        {
            if (pokemon.Ability == null)
                return false;

            if (weatherData.DamageImmunityAbilities == null || weatherData.DamageImmunityAbilities.Length == 0)
                return false;

            string abilityName = pokemon.Ability.Name;
            foreach (var immuneAbility in weatherData.DamageImmunityAbilities)
            {
                if (abilityName.Equals(immuneAbility, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }

        /// <summary>
        /// Calculates weather damage based on Max HP and damage fraction.
        /// </summary>
        private int CalculateWeatherDamage(int maxHP, float damageFraction)
        {
            int damage = (int)(maxHP * damageFraction);
            return Math.Max(1, damage);
        }

        /// <summary>
        /// Gets the appropriate localization key for weather damage.
        /// </summary>
        private string GetWeatherDamageMessageKey(Weather weather)
        {
            switch (weather)
            {
                case Weather.Sandstorm:
                    return LocalizationKey.WeatherSandstormDamage;
                case Weather.Hail:
                    return LocalizationKey.WeatherHailDamage;
                default:
                    return LocalizationKey.WeatherSandstormDamage; // Fallback
            }
        }

        /// <summary>
        /// Creates a DamageAction for status damage using DamageContextFactory.
        /// </summary>
        private DamageAction CreateStatusDamageAction(BattleSlot slot, BattleField field, int damage)
        {
            var context = _damageContextFactory.CreateForStatusDamage(slot, damage, field);
            return new DamageAction(slot, slot, context);
        }
    }
}
