using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Foundation.Field;
using PokemonUltimate.Combat.Results;

namespace PokemonUltimate.Combat.Statistics
{
    /// <summary>
    /// Observer for battle actions - receives notifications when actions execute.
    /// Used for statistics collection, logging, debugging, etc.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.20: Statistics System
    /// **Documentation**: See `docs/features/2-combat-system/2.20-statistics-system/architecture.md`
    /// </remarks>
    public interface IBattleActionObserver
    {
        /// <summary>
        /// Called when an action's logic is executed.
        /// </summary>
        /// <param name="action">The action that was executed.</param>
        /// <param name="field">The battlefield.</param>
        /// <param name="reactions">The reactions generated by the action.</param>
        void OnActionExecuted(BattleAction action, BattleField field, IEnumerable<BattleAction> reactions);
        
        /// <summary>
        /// Called when a battle turn starts.
        /// </summary>
        /// <param name="turnNumber">The turn number (1-based).</param>
        /// <param name="field">The battlefield.</param>
        void OnTurnStart(int turnNumber, BattleField field);
        
        /// <summary>
        /// Called when a battle turn ends.
        /// </summary>
        /// <param name="turnNumber">The turn number (1-based).</param>
        /// <param name="field">The battlefield.</param>
        void OnTurnEnd(int turnNumber, BattleField field);
        
        /// <summary>
        /// Called when a battle starts.
        /// </summary>
        /// <param name="field">The battlefield.</param>
        void OnBattleStart(BattleField field);
        
        /// <summary>
        /// Called when a battle ends.
        /// </summary>
        /// <param name="outcome">The battle outcome.</param>
        /// <param name="field">The battlefield.</param>
        void OnBattleEnd(BattleOutcome outcome, BattleField field);
    }
}

