using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Foundation.Field;

namespace PokemonUltimate.Combat.Statistics
{
    /// <summary>
    /// Interface for modular statistics trackers.
    /// Makes it easy to add new tracking types without modifying core collector.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.20: Statistics System
    /// **Documentation**: See `docs/features/2-combat-system/2.20-statistics-system/architecture.md`
    /// </remarks>
    public interface IStatisticsTracker
    {
        /// <summary>
        /// Tracks statistics for the given action and reactions.
        /// </summary>
        /// <param name="action">The action that was executed.</param>
        /// <param name="field">The battlefield.</param>
        /// <param name="reactions">The reactions generated by the action.</param>
        /// <param name="stats">The statistics object to update.</param>
        void TrackAction(BattleAction action, BattleField field, IEnumerable<BattleAction> reactions, BattleStatistics stats);
    }
}

