using System;
using System.Collections.Generic;
using System.Linq;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Extensions;
using PokemonUltimate.Core.Blueprints;
using PokemonUltimate.Core.Instances;

namespace PokemonUltimate.Combat.Events
{
    /// <summary>
    /// Processes battle triggers and notifies all listeners (abilities, items).
    /// Collects actions from listeners and returns them for queue processing.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.9: Abilities & Items
    /// **Documentation**: See `docs/features/2-combat-system/2.9-abilities-items/architecture.md`
    /// </remarks>
    public class BattleTriggerProcessor : IBattleTriggerProcessor
    {
        private readonly IBattleEventBus _eventBus;

        /// <summary>
        /// Creates a new battle trigger processor.
        /// </summary>
        /// <param name="eventBus">Optional event bus. If null, uses direct listener creation (legacy mode).</param>
        public BattleTriggerProcessor(IBattleEventBus eventBus = null)
        {
            _eventBus = eventBus;
        }

        /// <summary>
        /// Processes a battle trigger for all active Pokemon on the field.
        /// Returns actions generated by abilities and items.
        /// </summary>
        /// <param name="trigger">The battle event that occurred.</param>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>Actions to execute, ordered by speed (fastest first).</returns>
        /// <exception cref="ArgumentNullException">If field is null.</exception>
        public List<BattleAction> ProcessTrigger(BattleTrigger trigger, BattleField field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field), Core.Constants.ErrorMessages.FieldCannotBeNull);

            var actions = new List<BattleAction>();

            // If event bus is available, use it for published events
            // However, we still need to process slot-specific listeners
            if (_eventBus != null)
            {
                var busActions = _eventBus.Publish(trigger, field);
                actions.AddRange(busActions);
            }

            // Get all active slots ordered by speed (fastest first)
            var activeSlots = field.GetAllActiveSlots()
                .Where(slot => slot.IsActive())
                .OrderByDescending(slot => slot.Pokemon.GetEffectiveStat(Core.Enums.Stat.Speed))
                .ToList();

            foreach (var slot in activeSlots)
            {
                var pokemon = slot.Pokemon;

                // Process ability
                if (pokemon.Ability != null)
                {
                    var abilityListener = new AbilityListener(pokemon.Ability);
                    var abilityActions = abilityListener.OnTrigger(trigger, slot, field);
                    actions.AddRange(abilityActions);
                }

                // Process held item
                if (pokemon.HeldItem != null)
                {
                    var itemListener = new ItemListener(pokemon.HeldItem);
                    var itemActions = itemListener.OnTrigger(trigger, slot, field);
                    actions.AddRange(itemActions);
                }
            }

            return actions;
        }
    }
}

