using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;

namespace PokemonUltimate.Combat.Events
{
    /// <summary>
    /// Interface for processing battle triggers and notifying listeners (abilities, items).
    /// Collects actions from listeners and returns them for queue processing.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.9: Abilities & Items
    /// **Documentation**: See `docs/features/2-combat-system/2.9-abilities-items/architecture.md`
    /// </remarks>
    public interface IBattleTriggerProcessor
    {
        /// <summary>
        /// Processes a battle trigger for all active Pokemon on the field.
        /// Returns actions generated by abilities and items.
        /// </summary>
        /// <param name="trigger">The battle event that occurred.</param>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>Actions to execute, ordered by speed (fastest first).</returns>
        List<BattleAction> ProcessTrigger(BattleTrigger trigger, BattleField field);
    }
}
