using System;
using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;

namespace PokemonUltimate.Combat.Events
{
    /// <summary>
    /// Interface for subscribing to battle events (statistics/logging).
    /// </summary>
    public interface IBattleEventSubscriber
    {
        /// <summary>
        /// Called when a battle event is published.
        /// </summary>
        /// <param name="event">The event that occurred.</param>
        void OnBattleEvent(BattleEvent @event);
    }

    /// <summary>
    /// Unified interface for battle event bus that manages all types of battle events.
    /// Handles both BattleTrigger events (for abilities/items) and BattleEvent events (for statistics/logging).
    /// Provides decoupled communication between battle components.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.9: Abilities & Items, 2.20: Statistics System
    /// **Documentation**: See `docs/features/2-combat-system/2.9-abilities-items/architecture.md` and `docs/features/2-combat-system/2.20-statistics-system/architecture.md`
    /// </remarks>
    public interface IBattleEventBus
    {
        // ===== BattleTrigger Events (for abilities/items) =====

        /// <summary>
        /// Subscribes a listener to a specific battle trigger.
        /// </summary>
        /// <param name="trigger">The trigger to subscribe to.</param>
        /// <param name="listener">The listener to subscribe. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">If listener is null.</exception>
        void Subscribe(BattleTrigger trigger, IBattleListener listener);

        /// <summary>
        /// Unsubscribes a listener from a specific battle trigger.
        /// </summary>
        /// <param name="trigger">The trigger to unsubscribe from.</param>
        /// <param name="listener">The listener to unsubscribe. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">If listener is null.</exception>
        void Unsubscribe(BattleTrigger trigger, IBattleListener listener);

        /// <summary>
        /// Unsubscribes a listener from all triggers.
        /// </summary>
        /// <param name="listener">The listener to unsubscribe. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">If listener is null.</exception>
        void UnsubscribeAll(IBattleListener listener);

        /// <summary>
        /// Publishes a battle trigger event and returns actions from all subscribed listeners.
        /// </summary>
        /// <param name="trigger">The trigger to publish.</param>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>Actions generated by all listeners subscribed to this trigger.</returns>
        /// <exception cref="ArgumentNullException">If field is null.</exception>
        IEnumerable<BattleAction> Publish(BattleTrigger trigger, BattleField field);

        // ===== BattleEvent Events (for statistics/logging) =====

        /// <summary>
        /// Publishes a battle event (for statistics/logging).
        /// </summary>
        /// <param name="event">The event to publish.</param>
        void PublishEvent(BattleEvent @event);

        /// <summary>
        /// Subscribes a component to receive battle events (statistics/logging).
        /// </summary>
        /// <param name="subscriber">The subscriber to add.</param>
        void Subscribe(IBattleEventSubscriber subscriber);

        /// <summary>
        /// Unsubscribes a component from receiving battle events.
        /// </summary>
        /// <param name="subscriber">The subscriber to remove.</param>
        void Unsubscribe(IBattleEventSubscriber subscriber);
    }
}
