using System;
using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;

namespace PokemonUltimate.Combat.Events
{
    /// <summary>
    /// Interface for a battle event bus that manages subscriptions and event publishing.
    /// Provides decoupled communication between battle components.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.9: Abilities & Items
    /// **Documentation**: See `docs/features/2-combat-system/2.9-abilities-items/architecture.md`
    /// </remarks>
    public interface IBattleEventBus
    {
        /// <summary>
        /// Subscribes a listener to a specific battle trigger.
        /// </summary>
        /// <param name="trigger">The trigger to subscribe to.</param>
        /// <param name="listener">The listener to subscribe. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">If listener is null.</exception>
        void Subscribe(BattleTrigger trigger, IBattleListener listener);

        /// <summary>
        /// Unsubscribes a listener from a specific battle trigger.
        /// </summary>
        /// <param name="trigger">The trigger to unsubscribe from.</param>
        /// <param name="listener">The listener to unsubscribe. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">If listener is null.</exception>
        void Unsubscribe(BattleTrigger trigger, IBattleListener listener);

        /// <summary>
        /// Unsubscribes a listener from all triggers.
        /// </summary>
        /// <param name="listener">The listener to unsubscribe. Cannot be null.</param>
        /// <exception cref="ArgumentNullException">If listener is null.</exception>
        void UnsubscribeAll(IBattleListener listener);

        /// <summary>
        /// Publishes a battle trigger event and returns actions from all subscribed listeners.
        /// </summary>
        /// <param name="trigger">The trigger to publish.</param>
        /// <param name="field">The battlefield. Cannot be null.</param>
        /// <returns>Actions generated by all listeners subscribed to this trigger.</returns>
        /// <exception cref="ArgumentNullException">If field is null.</exception>
        IEnumerable<BattleAction> Publish(BattleTrigger trigger, BattleField field);
    }
}
