using System.Collections.Generic;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Foundation.Field;
using PokemonUltimate.Combat.Statistics.Definition;

namespace PokemonUltimate.Combat.Statistics.Trackers
{
    /// <summary>
    /// Tracks persistent status effect applications.
    /// </summary>
    /// <remarks>
    /// **Feature**: 2: Combat System
    /// **Sub-Feature**: 2.20: Statistics System
    /// **Documentation**: See `docs/features/2-combat-system/2.20-statistics-system/architecture.md`
    /// </remarks>
    internal class StatusEffectTracker : IStatisticsTracker
    {
        public void TrackAction(BattleAction action, BattleField field, IEnumerable<BattleAction> reactions, BattleStatistics stats)
        {
            if (action == null || stats == null || field == null)
                return;

            // Track status from ApplyStatusAction when it's executed as a main action
            // Do NOT count reactions here - they will be counted when they execute as main actions
            // This prevents double-counting: reactions are generated by other actions and will be
            // processed separately by the queue, at which point they'll be counted here
            if (action is ApplyStatusAction statusAction && statusAction.Target?.Pokemon != null)
            {
                // Use Species.Name for statistics accumulation across multiple battles
                var pokemonKey = statusAction.Target.Pokemon.Species.Name;
                var statusName = statusAction.Status.ToString();

                if (!string.IsNullOrEmpty(statusName) && statusName != "None")
                {
                    if (!stats.StatusEffectStats.ContainsKey(pokemonKey))
                        stats.StatusEffectStats[pokemonKey] = new Dictionary<string, int>();

                    if (!stats.StatusEffectStats[pokemonKey].ContainsKey(statusName))
                        stats.StatusEffectStats[pokemonKey][statusName] = 0;

                    stats.StatusEffectStats[pokemonKey][statusName]++;
                }
            }
        }
    }
}

