using System;
using System.Collections.Generic;
using System.Linq;
using PokemonUltimate.BattleSimulator.Helpers;
using PokemonUltimate.Combat;
using PokemonUltimate.Combat.Actions;
using PokemonUltimate.Combat.Damage;
using PokemonUltimate.Combat.Events;
using PokemonUltimate.Combat.Statistics;
using PokemonUltimate.Core.Data.Enums;
using PokemonUltimate.Core.Infrastructure.Localization;
using PokemonUltimate.Core.Domain.Instances;
using PokemonUltimate.Core.Services;
using PokemonUltimate.Core.Utilities.Extensions;
using PokemonInstance = PokemonUltimate.Core.Domain.Instances.Pokemon.PokemonInstance;

namespace PokemonUltimate.BattleSimulator.Logging
{
    /// <summary>
    /// Observer that publishes battle events when actions are executed.
    /// Acts as a bridge between the action observer system and the event system.
    /// </summary>
    /// <remarks>
    /// **Feature**: 6: Development Tools
    /// **Sub-Feature**: 6.8: Interactive Battle Simulator
    /// **Documentation**: See `docs/features/6-development-tools/6.8-interactive-battle-simulator/README.md`
    /// </remarks>
    public class DetailedBattleLoggerObserver : IBattleActionObserver
    {
        private readonly UIBattleLogger _logger;
        private readonly ILocalizationProvider _localizationProvider;
        private readonly IBattleEventBus _eventBus;
        private int _currentTurn = 0;
        private Dictionary<string, string>? _pokemonNameMapping;

        public DetailedBattleLoggerObserver(UIBattleLogger logger, IBattleEventBus eventBus = null)
        {
            _logger = logger ?? throw new System.ArgumentNullException(nameof(logger));
            _localizationProvider = LocalizationService.Instance;
            _eventBus = eventBus;

            // Get name mapping from logger if available
            _pokemonNameMapping = logger.GetPokemonNameMapping();
        }

        private string GetPokemonDisplayName(PokemonInstance? pokemon)
        {
            if (pokemon == null)
                return "Unknown";

            return PokemonNameMapper.GetDisplayName(pokemon, _pokemonNameMapping);
        }

        public void OnActionExecuted(BattleAction action, BattleField field, IEnumerable<BattleAction> reactions)
        {
            if (action == null || field == null)
                return;

            // Publish events based on action type (event-driven approach)
            switch (action)
            {
                case UseMoveAction moveAction:
                    PublishMoveUsedEvent(moveAction, field);
                    // Publish actions generated by this move
                    PublishActionsGeneratedEvent(moveAction, reactions, field);
                    break;

                case DamageAction damageAction:
                    PublishDamageDealtEvent(damageAction, field);
                    break;

                case FaintAction faintAction:
                    PublishPokemonFaintedEvent(faintAction, field);
                    break;

                case SwitchAction switchAction:
                    // Use OldPokemon property which is set during ExecuteLogic
                    // This is the Pokemon that was switched out
                    PublishPokemonSwitchedEvent(switchAction, field, switchAction.OldPokemon);
                    break;

                case HealAction healAction:
                    PublishPokemonHealedEvent(healAction, field);
                    break;

                case StatChangeAction statAction:
                    // Stat changes are less critical, can be logged directly or published as events
                    LogStatChangeAction(statAction, field);
                    break;

                case ApplyStatusAction statusAction:
                    // Status changes can be published as events
                    PublishStatusAppliedEvent(statusAction, field);
                    break;

                case MessageAction messageAction:
                    // Log important messages (paralysis preventing movement, sleep, etc.)
                    LogMessageAction(messageAction, field);
                    break;
            }

            // Publish reaction events if any
            if (reactions != null && reactions.Any() && _eventBus != null)
            {
                foreach (var reaction in reactions)
                {
                    if (reaction is FaintAction faintReaction)
                    {
                        // Reaction will be logged when the FaintAction executes
                        // No need to log here as it will be handled by the event system
                    }
                }
            }
        }

        private void PublishMoveUsedEvent(UseMoveAction action, BattleField field)
        {
            if (action.User?.Pokemon == null || action.Target?.Pokemon == null || _eventBus == null)
                return;

            var moveName = action.Move.GetDisplayName(_localizationProvider);
            var @event = new BattleEvent(
                BattleEventType.MoveUsed,
                turnNumber: _currentTurn,
                isPlayerSide: action.User.Side.IsPlayer,
                pokemon: action.User.Pokemon,
                data: new BattleEventData
                {
                    MoveName = moveName,
                    MoveId = action.Move.Id,
                    TargetPokemon = action.Target.Pokemon
                });

            _eventBus.PublishEvent(@event);
        }

        private void PublishDamageDealtEvent(DamageAction action, BattleField field)
        {
            if (action.User?.Pokemon == null || action.Target?.Pokemon == null || action.Context == null || _eventBus == null)
                return;

            var context = action.Context;
            var move = context.Move;
            int damageDealt = context.FinalDamage;

            // Check if this is status damage (burn, poison, etc.)
            string moveName;
            bool isStatusDamage = move.Name == "Status Damage" || move.Name == "Entry Hazard";

            if (isStatusDamage && action.Target.Pokemon.Status != PersistentStatus.None)
            {
                // Use the status name instead of "Status Damage"
                moveName = action.Target.Pokemon.Status.GetDisplayName(_localizationProvider);
            }
            else
            {
                moveName = move.GetDisplayName(_localizationProvider);
            }

            // Calculate HP before and after
            int hpBefore = action.Target.Pokemon.CurrentHP + damageDealt;
            int hpAfter = action.Target.Pokemon.CurrentHP;

            // Determine if this is self-damage (status damage, recoil, etc.)
            // For status damage, User and Target are the same slot
            bool isSelfDamage = action.User == action.Target || action.User.Pokemon == action.Target.Pokemon;

            var @event = new BattleEvent(
                BattleEventType.DamageDealt,
                turnNumber: _currentTurn,
                isPlayerSide: action.User.Side.IsPlayer,
                pokemon: action.User.Pokemon,
                data: new BattleEventData
                {
                    MoveName = moveName,
                    MoveId = move.Id,
                    DamageAmount = damageDealt,
                    WasCritical = context.IsCritical,
                    TypeEffectiveness = context.TypeEffectiveness,
                    TargetPokemon = action.Target.Pokemon,
                    BaseDamage = context.BaseDamage,
                    Multiplier = context.Multiplier,
                    HpBefore = hpBefore,
                    HpAfter = hpAfter,
                    IsSelfDamage = isSelfDamage  // Store this info for logging
                });

            _eventBus.PublishEvent(@event);

            // Also publish critical hit event if applicable
            if (context.IsCritical)
            {
                _eventBus.PublishEvent(new BattleEvent(
                    BattleEventType.CriticalHit,
                    turnNumber: _currentTurn,
                    isPlayerSide: action.User.Side.IsPlayer,
                    pokemon: action.User.Pokemon,
                    data: new BattleEventData { MoveName = moveName }));
            }
        }

        private void PublishPokemonFaintedEvent(FaintAction action, BattleField field)
        {
            if (action.Target?.Pokemon == null || _eventBus == null)
                return;

            var fainted = action.Target.Pokemon;
            var side = action.Target.Side;
            int remainingPokemon = 0;
            int totalPokemon = 0;
            int faintedCount = 0;

            if (side.Party != null)
            {
                totalPokemon = side.Party.Count;
                faintedCount = side.Party.Count(p => p.IsFainted);
                remainingPokemon = totalPokemon - faintedCount;
            }

            var @event = new BattleEvent(
                BattleEventType.PokemonFainted,
                turnNumber: _currentTurn,
                isPlayerSide: side.IsPlayer,
                pokemon: fainted,
                data: new BattleEventData
                {
                    DefeatedBy = action.User?.Pokemon,
                    RemainingPokemon = remainingPokemon,
                    TotalPokemon = totalPokemon,
                    FaintedCount = faintedCount
                });

            _eventBus.PublishEvent(@event);
        }

        private void PublishPokemonSwitchedEvent(SwitchAction action, BattleField field, PokemonInstance oldPokemon)
        {
            if (action.Slot?.Side == null || action.NewPokemon == null || _eventBus == null)
                return;

            var side = action.Slot.Side;
            int remainingPokemon = 0;
            int totalPokemon = 0;
            int faintedCount = 0;

            if (side.Party != null)
            {
                totalPokemon = side.Party.Count;
                faintedCount = side.Party.Count(p => p.IsFainted);
                remainingPokemon = totalPokemon - faintedCount;
            }

            var @event = new BattleEvent(
                BattleEventType.PokemonSwitched,
                turnNumber: _currentTurn,
                isPlayerSide: side.IsPlayer,
                pokemon: action.NewPokemon,
                data: new BattleEventData
                {
                    SwitchedOut = oldPokemon,  // Use the captured old Pokemon, not the slot's current Pokemon
                    SwitchedIn = action.NewPokemon,
                    RemainingPokemon = remainingPokemon,
                    TotalPokemon = totalPokemon,
                    FaintedCount = faintedCount
                });

            _eventBus.PublishEvent(@event);
        }

        private void PublishPokemonHealedEvent(HealAction action, BattleField field)
        {
            if (action.Target?.Pokemon == null || _eventBus == null)
                return;

            var @event = new BattleEvent(
                BattleEventType.PokemonHealed,
                turnNumber: _currentTurn,
                isPlayerSide: action.Target.Side.IsPlayer,
                pokemon: action.Target.Pokemon,
                data: new BattleEventData
                {
                    HealAmount = action.Amount
                });

            _eventBus.PublishEvent(@event);
        }

        private void PublishStatusAppliedEvent(ApplyStatusAction action, BattleField field)
        {
            if (action.Target?.Pokemon == null || _eventBus == null)
                return;

            var statusName = action.Status.GetDisplayName(_localizationProvider);
            var @event = new BattleEvent(
                BattleEventType.PokemonStatusApplied,
                turnNumber: _currentTurn,
                isPlayerSide: action.Target.Side.IsPlayer,
                pokemon: action.Target.Pokemon,
                data: new BattleEventData
                {
                    StatusName = statusName
                });

            _eventBus.PublishEvent(@event);
        }

        private void PublishActionsGeneratedEvent(UseMoveAction moveAction, IEnumerable<BattleAction> generatedActions, BattleField field)
        {
            if (moveAction.User?.Pokemon == null || _eventBus == null)
                return;

            if (generatedActions == null || !generatedActions.Any())
                return;

            // Check if move missed (only MessageAction, no DamageAction)
            bool hasDamageAction = generatedActions.Any(a => a is DamageAction);
            bool hasMissMessage = generatedActions
                .OfType<MessageAction>()
                .Any(msg => msg.Message.Contains("missed", StringComparison.OrdinalIgnoreCase) ||
                           msg.Message.Contains("falló", StringComparison.OrdinalIgnoreCase) ||
                           msg.Message.Contains("fallo", StringComparison.OrdinalIgnoreCase));

            // If move missed, publish MoveMissed event
            if (!hasDamageAction && hasMissMessage)
            {
                var moveName = moveAction.Move.GetDisplayName(_localizationProvider);
                var missedEvent = new BattleEvent(
                    BattleEventType.MoveMissed,
                    turnNumber: _currentTurn,
                    isPlayerSide: moveAction.User.Side.IsPlayer,
                    pokemon: moveAction.User.Pokemon,
                    data: new BattleEventData
                    {
                        MoveName = moveName,
                        TargetPokemon = moveAction.Target?.Pokemon
                    });
                _eventBus.PublishEvent(missedEvent);
            }

            // Get action type names
            var actionTypes = generatedActions
                .Select(a => a.GetType().Name)
                .Distinct()
                .ToList();

            var actionTypesString = string.Join(", ", actionTypes);
            var actionCount = generatedActions.Count();

            var @event = new BattleEvent(
                BattleEventType.ActionsGenerated,
                turnNumber: _currentTurn,
                isPlayerSide: moveAction.User.Side.IsPlayer,
                pokemon: moveAction.User.Pokemon,
                data: new BattleEventData
                {
                    MoveName = moveAction.Move.GetDisplayName(_localizationProvider),
                    GeneratedActionTypes = actionTypesString,
                    GeneratedActionCount = actionCount
                });

            _eventBus.PublishEvent(@event);
        }

        private void LogHealAction(HealAction action, BattleField field)
        {
            if (action.Target?.Pokemon == null)
                return;

            var target = action.Target.Pokemon;
            var side = action.Target.Side.IsPlayer ? "Player" : "Enemy";
            var amount = action.Amount;

            _logger.LogInfo($"[{side}] {GetPokemonDisplayName(target)} recovered {amount} HP");
            _logger.LogDebug($"  HP: {target.CurrentHP}/{target.MaxHP}");
        }

        private void LogStatChangeAction(StatChangeAction action, BattleField field)
        {
            if (action.Target?.Pokemon == null)
                return;

            var target = action.Target.Pokemon;
            var side = action.Target.Side.IsPlayer ? "Player" : "Enemy";
            var stat = action.Stat;
            var change = action.Change;
            string direction = change > 0 ? "rose" : "fell";

            _logger.LogInfo($"[{side}] {GetPokemonDisplayName(target)}'s {stat} {direction} by {System.Math.Abs(change)} stage(s)");
        }

        private void LogStatusAction(ApplyStatusAction action, BattleField field)
        {
            if (action.Target?.Pokemon == null)
                return;

            var target = action.Target.Pokemon;
            var side = action.Target.Side.IsPlayer ? "Player" : "Enemy";
            var status = action.Status;
            var statusName = status.GetDisplayName(_localizationProvider);

            _logger.LogInfo($"[{side}] {GetPokemonDisplayName(target)} was afflicted with {statusName}");
        }

        public void OnTurnStart(int turnNumber, BattleField field)
        {
            _currentTurn = turnNumber;
            // Turn start event published by CombatEngine
            // Log Pokemon status at turn start (debug only)
            LogPokemonStatus(field);
        }

        public void OnTurnEnd(int turnNumber, BattleField field)
        {
            // Turn end event published by CombatEngine
            // Log Pokemon status at turn end (debug only)
            LogPokemonStatus(field);
        }

        public void OnBattleStart(BattleField field)
        {
            // Battle start event published by CombatEngine
            LogPokemonStatus(field);
        }

        public void OnBattleEnd(BattleOutcome outcome, BattleField field)
        {
            // Battle end event published by CombatEngine
            LogPokemonStatus(field);
        }

        private void LogMessageAction(MessageAction messageAction, BattleField field)
        {
            if (messageAction == null || string.IsNullOrEmpty(messageAction.Message))
                return;

            // Log important status-related messages (paralysis, sleep, freeze, etc.)
            // These messages are critical for debugging status effects
            var message = messageAction.Message;

            // Check if this is a status-related message that should be logged
            bool isStatusMessage = message.Contains("paralyzed", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("paralizado", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("asleep", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("dormido", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("frozen", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("congelado", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("can't move", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("no puede moverse", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("flinch", StringComparison.OrdinalIgnoreCase) ||
                message.Contains("retrocedió", StringComparison.OrdinalIgnoreCase);

            if (isStatusMessage)
            {
                string? pokemonName = null;
                bool isPlayerSide = false;

                // First, try to use the User from the action if available
                if (messageAction.User != null && messageAction.User.Pokemon != null)
                {
                    pokemonName = GetPokemonDisplayName(messageAction.User.Pokemon);
                    isPlayerSide = messageAction.User.Side.IsPlayer;
                }
                else
                {
                    // Fallback: Try to find the Pokemon mentioned in the message
                    foreach (var slot in field.PlayerSide.Slots)
                    {
                        if (!slot.IsEmpty && slot.Pokemon != null && message.Contains(slot.Pokemon.DisplayName, StringComparison.OrdinalIgnoreCase))
                        {
                            pokemonName = GetPokemonDisplayName(slot.Pokemon);
                            isPlayerSide = true;
                            break;
                        }
                    }

                    if (pokemonName == null)
                    {
                        foreach (var slot in field.EnemySide.Slots)
                        {
                            if (!slot.IsEmpty && slot.Pokemon != null && message.Contains(slot.Pokemon.DisplayName, StringComparison.OrdinalIgnoreCase))
                            {
                                pokemonName = GetPokemonDisplayName(slot.Pokemon);
                                isPlayerSide = false;
                                break;
                            }
                        }
                    }
                }

                var sideName = isPlayerSide ? "Player" : "Enemy";
                if (pokemonName != null)
                {
                    _logger.LogInfo($"[{sideName}] {pokemonName}: {message}");
                }
                else
                {
                    // Log anyway if we can't determine the Pokemon
                    _logger.LogInfo(message);
                }
            }
        }

        private void LogPokemonStatus(BattleField field)
        {
            // Log Player side
            foreach (var slot in field.PlayerSide.Slots)
            {
                if (!slot.IsEmpty && slot.Pokemon != null)
                {
                    var p = slot.Pokemon;
                    var statusName = p.Status.GetDisplayName(_localizationProvider);
                    _logger.LogDebug($"[Player] {GetPokemonDisplayName(p)} - HP: {p.CurrentHP}/{p.MaxHP}, Status: {statusName}");
                }
            }

            // Log Enemy side
            foreach (var slot in field.EnemySide.Slots)
            {
                if (!slot.IsEmpty && slot.Pokemon != null)
                {
                    var p = slot.Pokemon;
                    var statusName = p.Status.GetDisplayName(_localizationProvider);
                    _logger.LogDebug($"[Enemy] {GetPokemonDisplayName(p)} - HP: {p.CurrentHP}/{p.MaxHP}, Status: {statusName}");
                }
            }
        }
    }
}

